import { useEffect, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import type { JobAnalysis } from '../contracts/jobAnalysis'
import { Alert, CategoryScore, HardFilterStatusBadge, PageHeader, ScoreBadge, SectionCard } from '../components/ui'
import { useAppMode } from '../features/access/AppModeProvider'
import { localAnalysisRepository, supabaseAnalysisRepository } from '../features/analysis/analysisRepository'
import { loadHardFilterSession } from '../features/hardFilter/hardFilterSessionStorage'
import { findFilteredOffer } from '../features/offers/offerResultsAdapter'

export function OfferDetailsPage() {
  const { offerId } = useParams<{ offerId: string }>()
  const { mode, session } = useAppMode()
  const [analysis, setAnalysis] = useState<JobAnalysis | null>(null)
  const item = findFilteredOffer(loadHardFilterSession().session?.filteredOffers ?? [], offerId)
  useEffect(() => { const repository = mode === 'authenticated' && session ? supabaseAnalysisRepository(session.user) : localAnalysisRepository; void repository.load().then((items) => setAnalysis(items.find((entry) => entry.offerId === offerId) ?? null)) }, [mode, offerId, session])
  if (!item) return <Navigate to="/offers" replace />
  const { offer, result } = item
  return <section className="page page--wide"><Link className="back-link" to="/offers">← Wróć do wyników</Link><div className="details-heading"><PageHeader eyebrow="Szczegóły oferty" title={offer.title} intro={offer.company} />{analysis && <ScoreBadge score={analysis.overallScore} />}</div><div className="details-meta"><HardFilterStatusBadge status={result.status} /><span>Źródło: {analysis?.sourceQuality === 'full' ? 'pełna treść lokalna' : 'dane częściowe'}</span>{offer.location && <span>{offer.location}</span>}{offer.workMode && <span>{offer.workMode}</span>}{offer.contractType && <span>{offer.contractType}</span>}</div><SectionCard title="Twarde kryteria"><p>{result.reasons[0]?.label ?? 'Brak potwierdzonych konfliktów.'}</p><ul className="risk-list">{result.reasons.map((reason) => <li key={reason.code}>{reason.label}</li>)}</ul></SectionCard>{analysis ? <><SectionCard title="Analiza dopasowania" className="recommendation-panel"><p><strong>{analysis.recommendation}</strong> — {analysis.summary}</p><small>Wynik to wskazówka AI, nie obiektywna prawda. Wykonano: {new Date(analysis.createdAt).toLocaleString('pl-PL')}.</small></SectionCard><div className="details-grid"><SectionCard title="Oceny cząstkowe"><CategoryScore label="Doświadczenie" score={analysis.categoryScores.experience.score} /><p>{analysis.categoryScores.experience.rationale}</p><CategoryScore label="Umiejętności" score={analysis.categoryScores.skills.score} /><p>{analysis.categoryScores.skills.rationale}</p><CategoryScore label="Preferencje" score={analysis.categoryScores.preferences.score} /><p>{analysis.categoryScores.preferences.rationale}</p><CategoryScore label="Rozwój" score={analysis.categoryScores.growth.score} /><p>{analysis.categoryScores.growth.rationale}</p></SectionCard><SectionCard title="Ryzyka i braki"><h3>Ryzyka</h3><ul className="risk-list">{analysis.risks.map((entry) => <li key={entry}>{entry}</li>)}</ul><h3>Brakujące informacje</h3><ul className="missing-list">{analysis.missingInformation.map((entry) => <li key={entry}>{entry}</li>)}</ul></SectionCard></div><SectionCard title="Mocne strony"><ul className="check-list">{analysis.strengths.map((entry) => <li key={entry}>{entry}</li>)}</ul></SectionCard></> : <Alert title="Analiza nie jest jeszcze gotowa" tone="info">Oferta pozostaje widoczna z wynikiem Hard Filter. Kod diagnostyczny: ANALYSIS_NOT_STARTED. Wróć do importu i uruchom analizę ponownie.</Alert>}<div className="action-row"><Link className="button button--secondary" to="/offers">Wróć do listy</Link>{offer.sourceUrl && <a className="button button--secondary" href={offer.sourceUrl} target="_blank" rel="noreferrer">Otwórz ofertę źródłową</a>}</div></section>
}
