import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Alert, HardFilterStatusBadge, PageHeader, PrimaryLink, ScoreBadge } from '../components/ui'
import { useAppMode } from '../features/access/AppModeProvider'
import type { WorkspaceOfferListItem } from '../features/workspace/workspaceRepository'
import { workspaceRepositoryFor } from '../features/workspace/workspaceService'

const badgeStatus = (status?: 'pass' | 'needs_review' | 'fail') => status === 'needs_review' ? 'weak' : status ?? 'weak'
const reason = (item: WorkspaceOfferListItem) => { const value = item.hardFilter?.reasons[0]; return typeof value === 'object' && value && 'label' in value ? String(value.label) : item.hardFilter ? 'Wynik zapisany w workspace.' : 'Hard Filter nie został jeszcze uruchomiony.' }

export function OffersPage() {
  const { mode, session } = useAppMode(); const [items, setItems] = useState<WorkspaceOfferListItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showExcluded, setShowExcluded] = useState(false); const [filter, setFilter] = useState<'all' | 'pass' | 'needs_review' | 'fail'>('all')
  const load = useCallback(async () => { if (!mode) return; setLoading(true); setError(''); try { setItems(await workspaceRepositoryFor(mode, session?.user).loadOfferList()) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Nie udało się odczytać ofert workspace.') } finally { setLoading(false) } }, [mode, session])
  useEffect(() => { void load() }, [load])
  const mutate = async (action: (repository: ReturnType<typeof workspaceRepositoryFor>) => Promise<void>) => { if (!mode) return; try { await action(workspaceRepositoryFor(mode, session?.user)); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Nie udało się zapisać zmiany.') } }
  const visible = items.filter((item) => (showExcluded || item.userState?.lifecycleStatus !== 'excluded') && (filter === 'all' || item.hardFilter?.status === filter))
  if (loading) return <section className="page page--wide"><PageHeader eyebrow="Workspace" title="Wczytujemy oferty" intro="Odtwarzamy trwały stan workspace." /></section>
  if (error) return <section className="page page--wide"><PageHeader eyebrow="Workspace" title="Nie udało się odczytać ofert" intro="Spróbuj ponownie." /><Alert title="Błąd" tone="warning">{error}</Alert><button className="button button--primary" onClick={() => void load()}>Ponów</button></section>
  if (!items.length) return <section className="page page--wide"><PageHeader eyebrow="Wyniki ofert" title="Brak ofert w workspace" intro="Zaimportuj raport i uruchom Hard Filter." /><PrimaryLink to="/import">Przejdź do importu</PrimaryLink></section>
  return <section className="page page--wide"><PageHeader eyebrow="Workspace" title="Oferty do sprawdzenia" intro="Lista i szczegóły korzystają z tego samego trwałego modelu danych." /><div className="list-controls"><label>Hard Filter<select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">Wszystkie</option><option value="pass">Przechodzi</option><option value="needs_review">Wymaga sprawdzenia</option><option value="fail">Odrzucone</option></select></label><label><input type="checkbox" checked={showExcluded} onChange={(event) => setShowExcluded(event.target.checked)} /> Pokaż wykluczone</label></div><section className="offer-section"><div className="offer-list">{visible.map((item) => <article className="offer-card" key={item.offer.id}><div className="offer-card__header"><div className="offer-card__identity"><h2>{item.offer.title}</h2><p>{item.offer.company}</p></div><div className="offer-card__signal">{item.analysis ? <ScoreBadge score={item.analysis.overallScore} /> : <HardFilterStatusBadge status={badgeStatus(item.hardFilter?.status)} />}</div></div><div className="offer-card__meta"><HardFilterStatusBadge status={badgeStatus(item.hardFilter?.status)} /><span>{item.userState?.lifecycleStatus ?? 'new'}</span>{item.offer.location && <span>{item.offer.location}</span>}{item.userState?.favorite && <span>★ Ulubiona</span>}{item.userState?.applied && <span>Aplikowano</span>}</div><p className="risk-summary">{reason(item)}</p><div className="action-row"><Link className="text-link" to={`/offers/${item.offer.id}`}>Zobacz szczegóły →</Link><button className="button button--secondary" onClick={() => void mutate((repository) => repository.setFavorite(item.offer.id, !item.userState?.favorite))}>{item.userState?.favorite ? 'Usuń z ulubionych' : 'Ulubiona'}</button><button className="button button--secondary" onClick={() => void mutate((repository) => repository.setApplied(item.offer.id, !item.userState?.applied))}>{item.userState?.applied ? 'Cofnij aplikowanie' : 'Aplikowano'}</button>{item.userState?.lifecycleStatus === 'excluded' ? <button className="button button--secondary" onClick={() => void mutate((repository) => repository.restoreOffer(item.offer.id))}>Przywróć</button> : <button className="button button--secondary" onClick={() => void mutate((repository) => repository.excludeOffer(item.offer.id))}>Wyklucz</button>}</div></article>)}</div>{!visible.length && <Alert title="Brak ofert dla wybranego filtra" tone="info">Zmień filtr albo pokaż wykluczone oferty.</Alert>}</section></section>
}
