export type DemoStatus = 'worth' | 'review' | 'rejected'

export type DemoOffer = {
  id: string
  title: string
  company: string
  location: string
  workMode: string
  contractType: string
  seniority: string
  salary?: string
  sourceUrl?: string
  sourceState: 'fallback' | 'partial'
  facts: { summary: string; responsibilities: string[]; requirements: string[]; missingInformation: string[] }
  demoAssessment: {
    score: number
    status: DemoStatus
    recommendation: string
    primaryRisk: string
    strengths: string[]
    risks: string[]
    categoryScores: { experience: number; skills: number; preferences: number; growth: number }
  }
}

// Fakty pochodzą z pięciu plików .md z rocketjobs.zip. `demoAssessment` to statyczna interpretacja UI Checkpointu 2.
export const demoOffers: DemoOffer[] = [
  { id: 'tagvenue-performance-marketing-manager', title: 'Performance Marketing Manager', company: 'Tagvenue', location: 'Kraków', workMode: 'Praca w pełni zdalna', contractType: 'B2B, pełny etat', seniority: 'Starszy specjalista / Senior', sourceUrl: 'https://rocketjobs.pl/oferta-pracy/tagvenue-performance-marketing-manager-krakow-bi-data?utm_source=mail&utm_medium=jobalert&utm_medium=email&utm_campaign=bi-data%3Futm_source%3Ddop', sourceState: 'fallback', facts: { summary: 'Rozwój płatnej akwizycji, optymalizacja kampanii oraz praca z metrykami CAC, LTV i payback.', responsibilities: ['Skalowanie kanałów Google Ads i Meta', 'Budowa systemu raportowania KPI biznesowych', 'Prowadzenie testów i ocena incrementality'], requirements: ['5+ lat doświadczenia w performance marketingu', 'Google Ads i Meta Ads', 'Znajomość CAC, LTV oraz value-based bidding', 'Angielski na poziomie C1'], missingInformation: ['Brak widełek wynagrodzenia w materiale demonstracyjnym'] }, demoAssessment: { score: 58, status: 'review', recommendation: 'Warto sprawdzić, jeśli doświadczenie obejmuje skalowanie płatnej akwizycji.', primaryRisk: 'Wymagane jest co najmniej 5 lat specjalistycznego doświadczenia marketingowego.', strengths: ['Praca w pełni zdalna', 'B2B zgodne z preferencjami demonstracyjnymi'], risks: ['Profil roli jest wyraźnie marketingowy', 'Brak podanego wynagrodzenia'], categoryScores: { experience: 52, skills: 55, preferences: 82, growth: 68 } } },
  { id: 'admind-systems-automation-specialist', title: 'Systems & Automation Specialist', company: 'Admind', location: 'Kraków + 4 lokalizacje', workMode: 'Praca w pełni zdalna', contractType: 'Freelance, UZ, B2B', seniority: 'Specjalista / Mid', sourceState: 'fallback', facts: { summary: 'Część etatu lub współpraca projektowa przy dashboardach, automatyzacjach i ekosystemie narzędzi operacyjnych.', responsibilities: ['Utrzymanie danych i dashboardów dla leadershipu', 'Eliminowanie ręcznej pracy przez workflow', 'Wdrażanie alertów i narzędzi AI'], requirements: ['3–5+ lat w operations technology, RevOps lub data engineering', 'HubSpot lub Scoro', 'Automatyzacje i pipeline’y danych', 'Angielski'], missingInformation: ['Link źródłowy niedostępny w materiale demonstracyjnym', 'Brak widełek wynagrodzenia'] }, demoAssessment: { score: 86, status: 'worth', recommendation: 'Mocne dopasowanie do pracy z automatyzacją, dashboardami i procesami operacyjnymi.', primaryRisk: 'Współpraca jest częścią etatu lub projektowa, a nie pełnoetatowa.', strengths: ['Zakres obejmuje automatyzacje i dane operacyjne', 'Elastyczne formy współpracy', 'Praca zdalna'], risks: ['Wymagane doświadczenie ze Scoro lub HubSpot', 'Niepełny wymiar współpracy'], categoryScores: { experience: 84, skills: 89, preferences: 90, growth: 79 } } },
  { id: 'primaris-digital-terms-policies-specialist', title: 'Digital Terms & Policies Specialist', company: 'Primaris Services Sp. z o.o.', location: 'Warszawa', workMode: 'Zdalnie, spotkania w biurze raz w miesiącu', contractType: 'B2B, pełny etat', seniority: 'Specjalista / Mid', salary: '120–140 PLN netto + VAT/h', sourceUrl: 'https://rocketjobs.pl/oferta-pracy/primaris-services-sp-z-o-o--digital-terms-policies-specialist-warszawa-bi-data-69500cca?utm_source=mail&utm_medium=jobalert&utm_medium=email&utm_campaign=bi-data%3Futm_source%3Ddop', sourceState: 'fallback', facts: { summary: 'Dokumentacja regulacyjna bankowości internetowej i mobilnej, w tym PSD2, RODO i współpraca z compliance.', responsibilities: ['Analiza wpływu zmian na regulaminy', 'Definiowanie wymagań regulacyjnych', 'Współpraca z biznesem, IT, product ownerami i compliance'], requirements: ['4 lata doświadczenia komercyjnego', 'Sektor bankowy lub finansowy', 'PSD2 i RODO', 'Jira oraz Confluence jako atut'], missingInformation: ['Brak informacji o pełnym zakresie benefitów'] }, demoAssessment: { score: 41, status: 'rejected', recommendation: 'Oferta pozostaje widoczna, ale demonstracyjnie nie spełnia kluczowego kierunku automatyzacji i BI.', primaryRisk: 'Wymaga specjalistycznego doświadczenia bankowego i regulacyjnego.', strengths: ['B2B i praca głównie zdalna', 'Podane widełki godzinowe'], risks: ['Specjalizacja regulacyjna', 'Wymóg doświadczenia w bankowości lub finansach'], categoryScores: { experience: 30, skills: 34, preferences: 75, growth: 48 } } },
  { id: 'flying-bisons-bi-automation-specialist', title: 'Freelance BI & Automation Specialist', company: 'Flying Bisons', location: 'Łódź + 5 lokalizacji', workMode: 'Praca w pełni zdalna', contractType: 'Freelance, B2B', seniority: 'Specjalista / Mid', sourceUrl: 'https://rocketjobs.pl/oferta-pracy/flying-bisons-freelance-bi-automation-specialist-lodz-bi-data?utm_source=mail&utm_medium=jobalert&utm_medium=email&utm_campaign=bi-data%3Futm_source%3Ddop', sourceState: 'fallback', facts: { summary: 'Współpraca freelance przy dashboardach, strukturze danych i automatyzacjach dla Business Intelligence i Operations.', responsibilities: ['Budowa dashboardów w Looker Studio', 'Automatyzacje w Google Workspace i AppScript', 'Integracje z HubSpot, Atlassian i Slackiem'], requirements: ['Zaawansowany Google Sheets i AppScript', 'Looker Studio', 'Automatyzacje typu Zapier', 'Angielski w pracy zdalnej'], missingInformation: ['Brak widełek wynagrodzenia w materiale demonstracyjnym'] }, demoAssessment: { score: 92, status: 'worth', recommendation: 'Najmocniejsze demonstracyjne dopasowanie do pracy z BI, automatyzacją i zdalną współpracą.', primaryRisk: 'Forma freelance może oznaczać zmienny wymiar zleceń.', strengths: ['Bezpośredni zakres BI i automatyzacji', 'B2B oraz pełna praca zdalna', 'Integracje narzędzi SaaS'], risks: ['Współpraca on-demand', 'Brak podanych widełek wynagrodzenia'], categoryScores: { experience: 90, skills: 95, preferences: 94, growth: 87 } } },
  { id: 'tagvenue-product-operations-intern', title: 'Product Operations Intern', company: 'Tagvenue', location: 'Kraków', workMode: 'Praca w pełni zdalna', contractType: 'Praktyka / staż, UZ', seniority: 'Praktykant', salary: '31,40 PLN/h brutto', sourceUrl: 'https://rocketjobs.pl/oferta-pracy/tagvenue-product-operations-intern-krakow-bi-data?utm_source=mail&utm_medium=jobalert&utm_medium=email&utm_campaign=bi-data%3Futm_source%3Ddop', sourceState: 'partial', facts: { summary: 'Sześciomiesięczny płatny staż Product Operations z zadaniami w obszarze jakości, promptów, AI i automatyzacji procesów.', responsibilities: ['Rozwój procesów i quality assurance', 'Tworzenie oraz testowanie promptów AI', 'Automatyzacja powtarzalnych zadań'], requirements: ['Aktualny status studenta', 'Angielski w mowie i piśmie', 'Dostępność minimum 30 godzin tygodniowo', 'Chęć rozwoju w AI Operations'], missingInformation: ['Analiza na podstawie częściowych danych demonstracyjnych'] }, demoAssessment: { score: 66, status: 'review', recommendation: 'Ciekawa ścieżka rozwoju w AI Operations, wymagająca potwierdzenia statusu studenta i dostępności.', primaryRisk: 'Oferta wymaga statusu studenta oraz minimum 30 godzin tygodniowo.', strengths: ['Zadania z AI i automatyzacji', 'Mentoring oraz praca zdalna', 'Podana stawka'], risks: ['Wymagany status studenta', 'Poziom stażowy'], categoryScores: { experience: 58, skills: 67, preferences: 78, growth: 90 } } },
]

export const statusMeta: Record<DemoStatus, { label: string; symbol: string }> = { worth: { label: 'Warto aplikować', symbol: '✓' }, review: { label: 'Wymaga sprawdzenia', symbol: '?' }, rejected: { label: 'Odrzucona', symbol: '×' } }
export function findDemoOffer(id: string | undefined) { return demoOffers.find((offer) => offer.id === id) }
